### ISSUE TITLE
Exception: Unable to save page Latin/ecce hic

### ISSUE THREAD

**Issue by BenQuigley** [nyg/wiktionary-to-kindle#10]
Nice program! Thanks for publishing the output of the script as well as the build process, because the build failed on my machine:

```
Dec 27, 2024 10:01:24 AM de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser onPageEnd
INFO: Parsed 7950000 pages
Dec 27, 2024 10:01:26 AM de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser onPageEnd
INFO: Parsed 7975000 pages
Exception in thread "main" de.tudarmstadt.ukp.jwktl.api.WiktionaryException: Unable to save page Latin/ecce hic
        at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.saveParsedWiktionaryPage(WiktionaryArticleParser.java:155)
        at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.onPageEnd(WiktionaryArticleParser.java:104)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser.onPageEnd(WiktionaryDumpParser.java:190)
        at de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser.onElementEnd(WiktionaryDumpParser.java:151)
        at de.tudarmstadt.ukp.jwktl.parser.XMLDumpParser$XMLDumpHandler.endElement(XMLDumpParser.java:83)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:197)
        at de.tudarmstadt.ukp.jwktl.parser.XMLDumpParser.parseStream(XMLDumpParser.java:130)
        at de.tudarmstadt.ukp.jwktl.parser.XMLDumpParser.parse(XMLDumpParser.java:121)
        at de.tudarmstadt.ukp.jwktl.parser.WiktionaryDumpParser.parse(WiktionaryDumpParser.java:78)
        at de.tudarmstadt.ukp.jwktl.JWKTL.parseWiktionaryDump(JWKTL.java:140)
        at de.tudarmstadt.ukp.jwktl.JWKTL.parseWiktionaryDump(JWKTL.java:114)
        at edu.self.w2k.util.DumpUtil.parse(DumpUtil.java:146)
        at edu.self.w2k.CLI.main(CLI.java:40)
Caused by: com.sleepycat.je.UniqueConstraintException: (JE 5.0.73) Unique secondary key is already present
        at com.sleepycat.je.SecondaryDatabase.insertKey(SecondaryDatabase.java:997)
        at com.sleepycat.je.SecondaryDatabase.updateSecondary(SecondaryDatabase.java:857)
        at com.sleepycat.je.SecondaryTrigger.databaseUpdated(SecondaryTrigger.java:41)
        at com.sleepycat.je.Database.notifyTriggers(Database.java:2122)
        at com.sleepycat.je.Cursor.putNotify(Cursor.java:2136)
        at com.sleepycat.je.Cursor.putNoDups(Cursor.java:2052)
        at com.sleepycat.je.Cursor.putInternal(Cursor.java:2020)
        at com.sleepycat.je.Cursor.putNoOverwrite(Cursor.java:792)
        at com.sleepycat.persist.PrimaryIndex.put(PrimaryIndex.java:402)
        at com.sleepycat.persist.PrimaryIndex.put(PrimaryIndex.java:335)
        at de.tudarmstadt.ukp.jwktl.parser.WritableBerkeleyDBWiktionaryEdition.savePage(WritableBerkeleyDBWiktionaryEdition.java:219)
        at de.tudarmstadt.ukp.jwktl.parser.WiktionaryArticleParser.saveParsedWiktionaryPage(WiktionaryArticleParser.java:148)
        ... 24 more
pop-os:wiktionary-to-kindle > echo $?
1
```

**Comment by nyg** [comment]
Hello! It looks like the page "ecce hic" exists twice, maybe due to a redirection or something like that. I pushed a fix that avoids throwing an exception if the page can't be saved, so that the parsing can continue.

Let me know if you have other issues, I haven't used my program in a while 🙃.
